---
# samba4_ad_secondary_dcs/tasks/main.yml

- name: "Load variables"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "vars_{{ ansible_distribution }}.yml"
    - "vars_{{ ansible_os_family }}.yml"

- name: 'Create /etc/samba/rsync.pass'
  ansible.builtin.template:
    src: 'etc_samba_rsync_pass.j2'
    dest: '/etc/samba/rsync.pass'
    owner: 'root'
    group: 'root'
    mode: '0600'

- name: 'Create systemd service for samba4_sysvol_replication'
  ansible.builtin.template:
    src: 'etc_systemd_system_samba4_sysvol_replication.service.j2'
    dest: '/etc/systemd/system/samba4_sysvol_replication.service'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify:
    - 'Trigger systemctl daemon-reload'
    - 'Enable and start the samba4_sysvol_replication.timer'

- name: 'Create systemd timer for samba4_sysvol_replication'
  ansible.builtin.template:
    src: 'etc_systemd_system_samba4_sysvol_replication.timer.j2'
    dest: '/etc/systemd/system/samba4_sysvol_replication.timer'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify:
    - 'Trigger systemctl daemon-reload'
    - 'Enable and start the samba4_sysvol_replication.timer'
