---
# samba4_ad_secondary_dcs/handlers/main.yml

- name: 'Restart samba4_sysvol_replication.timer'
  service:
    name: 'samba4_sysvol_replication.timer'
    state: 'restarted'

- name: 'Trigger systemctl daemon-reload'
  ansible.builtin.systemd:
    daemon_reload: 'yes'

- name: 'Enable and start the samba4_sysvol_replication.timer'
  service:
    name: 'samba4_sysvol_replication.timer'
    state: 'started'
    enabled: 'true' 
